# K-Fold Iris Dataset ML

Use iris flower dataset from sklearn library and use cross_val_score against following models to measure the performance of each. In the end figure out the model with best performance,

1. Logistic Regression
2. SVM
3. Decision Tree
4. Random Forest

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_iris
import numpy as np

In [10]:
iris = load_iris()
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

#### Logistic Regression

In [11]:
lr_score = cross_val_score(LogisticRegression(), iris.data, iris.target)
lr_score

C:\Users\ashit\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [12]:
np.average(lr_score)

0.9733333333333334

#### Descision Tree

In [13]:
dt_score = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
dt_score

array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ])

In [14]:
np.average(dt_score)

0.9533333333333334

#### Support Vectore Machine

In [15]:
svm_score = cross_val_score(SVC(), iris.data, iris.target)
svm_score

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [16]:
np.average(svm_score)

0.9666666666666666

#### Random Forest Classifier

In [17]:
rf_score = cross_val_score(RandomForestClassifier(), iris.data, iris.target)
rf_score

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [18]:
np.average(rf_score)

0.9666666666666668

#### Best score is from Logistic Regression: 0.9733333333333334